// Generated by tools/generate_sbi_registry.py. Metadata only; no SBI records.
#pragma once
static constexpr SbiRequirement kSbiRequirements[] = {
    {712491360ULL, "dc3f29d7f7046fbdc85e8c376721a8880567f0cda309a52ee5da875ae9e40157", "ada8877a2a964eff2743d53cc043be0b7b148469b60de82fd1069f32700670eb", "Resident Evil 3: Nemesis", "SLES-02529"},
};
